data:
  path: "./data/german_credit_data.csv"
  test_size: 0.2

model:
  name: "svc-credit-risk-classifier"
  type: "SVC"
  C: 1.3
  kernel: "rbf"

mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "credit-risk-estimator"
  run_name: "svc-experiment"
  artifact_path: "model"
